name: Deployment Workflow

# Trigger this workflow on pushes to the specified branch
on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH Deploy
        # Use the 'appleboy/ssh-action' action for SSH deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }} # Your server's IP address
          username: ${{ secrets.USERNAME }} # Your server's username
          key: ${{ secrets.SSH_PRIVATE_KEY }} # Your server's SSH private key
          debug: true
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd next-with-gh-actions/ # Specify the path to your app directory on the server
            git pull origin staging
            npm ci
            npm run build
            pm2 restart ecosystem.config.js # Replace with your PM2 service name
